добавил секцию подвала
Irinka1010/IceCream pull request #12
Opened 2022-05-10 00:56 UTC by internet-user-0

добавил svg иконки к спрайту

2022-05-10 07:13 UTC, Irinka1010 reviewed
коментарі залишила, і прошу утрати секцію контакти з футера. Дякую

2022-05-10 07:13 UTC, Irinka1010 commented on src/sass/footer/_mobile-footer-two.scss
> +      width: 250px;
на планшентій версії маржен bottom-block__element не потрібен

2022-05-10 07:13 UTC, Irinka1010 commented on src/sass/footer/_mobile-footer.scss
> +   border-top: 1px solid #e1e1e1;
по макету   на 1280 відступ 60px

2022-05-10 10:19 UTC, internet-user-0 commented on src/sass/footer/_mobile-footer.scss
> +   border-top: 1px solid #e1e1e1;
исправил

2022-05-10 10:22 UTC, internet-user-0 commented on src/sass/footer/_mobile-footer-two.scss
> +      width: 250px;
исправил

2022-05-10 10:23 UTC, internet-user-0 commented on src/partials/footer.html
> +          <li class="netvork-list__item">
исправил

2022-05-10 10:26 UTC, internet-user-0 commented on src/sass/footer/_mobile-footer-netvork-panel.scss
> +}
исправил

2022-05-10 14:03 UTC, Zina88 commented on src/sass/footer/_mobile-footer.scss
> +      width: 200px;
тут лучше width: 180px поставить, не правильно переносится текст(если поставить применен letter-spacing)

2022-05-10 19:45 UTC, Irinka1010 requested changes

2022-05-10 19:45 UTC, Irinka1010 commented on src/sass/footer/_mobile-footer-netvork-panel.scss
> +   font-weight: 700;
для класу contact задати медіа правела на     font-size:  для таблетки і 1280

2022-05-10 19:45 UTC, Irinka1010 commented on src/sass/main.scss
> +// подвал
Дуже прошу зробити один паршал на  _footer.scss і його підключити

2022-05-11 09:40 UTC, Irinka1010 approved these changes

2022-05-11 09:55 UTC, merged