Feature/base
Irinka1010/IceCream pull request #3
Opened 2022-05-07 20:59 UTC by Irinka1010

Добавила базові стилі  файлі _base.scss і змінні _variables.scss. Як і просили назва  класу під заголовка label. Заголовка секції title. Якщо щось забула вкажіть .

2022-05-07 21:48 UTC, Zina88 requested changes

2022-05-07 21:48 UTC, Zina88 commented on src/sass/_base.scss
> +        width: 320px;
должно быть 480px

2022-05-07 21:48 UTC, Zina88 commented on src/index.html
> +
нет link на шрифты

2022-05-08 05:14 UTC, Irinka1010 commented on src/index.html
> +
шрифты уже в мейн подключины на прямую.

2022-05-08 05:16 UTC, Irinka1010 commented on src/sass/_base.scss
> +        width: 320px;
Я согласна но меня смущает что на макете на мобильной версии 320. Исправила.

2022-05-08 05:47 UTC, Anna-Chumakova commented on src/sass/_base.scss
> +    font-size: 16px;
думаю тут можно написать font-family:  'DM Sans'; 
    font-weight: ;
    line-height: ;
    letter-spacing: ;
    color: ;

2022-05-08 05:53 UTC, Anna-Chumakova approved these changes

2022-05-08 05:53 UTC, Anna-Chumakova commented on src/sass/_base.scss
> +    font-size: 16px;
увидела исправления

2022-05-08 05:54 UTC, Anna-Chumakova commented
вроде все добавила, можно еще visually hidden класс

2022-05-08 06:02 UTC, Irinka1010 commented on src/sass/_base.scss
> +    font-size: 16px;
добавила  font-weight: ;font-family: 'DM Sans'; остальное там было

2022-05-08 06:02 UTC, Irinka1010 commented on src/sass/_base.scss
> +    font-size: 16px;
Исправлено

2022-05-08 06:20 UTC, merged