розмітка секції Contacts
Irinka1010/IceCream pull request #5
Opened 2022-05-08 15:39 UTC by oksyluka

2022-05-08 17:49 UTC, Kateryna-Karetna commented on src/partials/contacts.html
> +        <p class="contacts__location">Chicago</p>
Робити все &lt;p&gt; не дуже семантично. Можна спробувати, наприклад, так: 
![Screenshot_1](https://user-images.githubusercontent.com/98160697/167308661-93a1e5d3-167e-459b-82f8-db16360104b6.jpg)

2022-05-08 18:31 UTC, Zina88 approved these changes

2022-05-09 07:56 UTC, oksyluka commented on src/partials/contacts.html
> +        <p class="contacts__location">Chicago</p>
Частково врахувала. Мені здається, тег time сюди не підходить, враховуючи приклади у специфікації

2022-05-09 10:35 UTC, Irinka1010 commented on src/partials/contacts.html
> +            <p class="contacts__hours-open">08:00 AM - 16:00 PM</p>
а можливо, давайте там де ми вказуємо час для симатики використаємо Тег <time> ,щоб читалка правельно прочитала цю інформацію

2022-05-09 13:33 UTC, Kateryna-Karetna reviewed
:+1:

2022-05-09 15:22 UTC, Irinka1010 commented on src/sass/_contacts.scss
> +.contacts__type {
Подивіться будь ласка, по макету розмір  її більший , можливо падінг поставити 20

2022-05-09 19:48 UTC, Kateryna-Karetna commented on src/partials/contacts.html
> +  <div class="container conteiner__contacts">
На container__contacts padding: 20px не потрібний - у вас уже на секції 15px. Звідси горизонтальний скрол з'являється

2022-05-09 19:48 UTC, Kateryna-Karetna commented on src/sass/_contacts.scss
> +.contacts {
Необхідно зробити сіткою

2022-05-10 06:36 UTC, oksyluka commented on src/partials/contacts.html
> +        <ul class="contats__time-open">
виправила

2022-05-10 06:39 UTC, oksyluka commented on src/partials/contacts.html
> +  <div class="container conteiner__contacts">
врахувала

2022-05-10 06:52 UTC, oksyluka commented on src/sass/_contacts.scss
> +.contacts {
Звісно, що сіткою зробити правильно. Але сітка є не лише у моїй секції, а ще у кількох. Правильно було б зробити єдину сітку і записати її як окремий scss-файл, а усім, у кого є сітка у секції, використовувати відповідні класи. А зараз, якщо я напишу класи grid і grid-item, і ще хтось так само, і при цьому форматування дещо відрізнятиметься, буде конфлікт.
До речі, властивості кнопки так само було б правильно прописати окремий файлом і викорисовувати усім. Всі кнопки ж однакові (принаймні мають такими бути).
Думаю, нам ментор зробити таке зауваження, і тоді виправимо.

2022-05-10 07:10 UTC, Zina88 requested changes

2022-05-10 07:10 UTC, Zina88 commented on src/sass/_contacts.scss
> +  border-bottom: 1px solid #e1e1e1;
нет бордеров на первых двух li

2022-05-10 07:10 UTC, Zina88 commented on src/partials/contacts.html
> +        <ul class="contats__time-open">
ошибка в имени класса, поэтому не применяются стили

2022-05-10 14:46 UTC, oksyluka commented on src/sass/_contacts.scss
> +  background-image: linear-gradient(#ffffff 15%, #fff5f6);
виправила, дякую!

2022-05-10 19:53 UTC, Irinka1010 approved these changes

2022-05-10 19:54 UTC, Irinka1010 approved these changes

2022-05-10 20:17 UTC, ksushavin commented
На секції, можливо, висота 100% не обов'язково.

На кнопці our locations - правий маржин, начебто краще, на лі поставити. 

На кнопках contacts__button {
    margin-left: auto;
    margin-right: auto;
начебто зайві... який їх функціонал?

2022-05-11 06:12 UTC, merged